#!/usr/bin/env bash
set -e

USER=team254
HOST=ec2.team254.com
APP=cheesy-mail

echo "Deploying $APP from Git master branch..."
echo
ssh $USER@$HOST "export GOPATH=/home/$USER/go && cd /opt/sites/$APP && git checkout -f && git pull && go get -d && go build && (pkill cheesy-mail || true) && (nohup ./cheesy-mail > /dev/null &)"
echo
echo "Deployed $APP."
